name: Zone2Monitor
options:
  bundleIdPrefix: com.moltenrooster
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

targets:
  Zone2Monitor:
    type: application
    platform: iOS
    sources:
      - Zone2Monitor
    info:
      path: Zone2Monitor/Info.plist
    settings:
      INFOPLIST_FILE: Zone2Monitor/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.moltenrooster.zone2monitor
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      DEVELOPMENT_TEAM: ""
    entitlements:
      path: Zone2Monitor/Zone2Monitor.entitlements
